### ISSUE TITLE
Support versioning of kustomization-base

### ISSUE THREAD

**Issue by micnncim** [spinnaker/kleat#121]
## Proposal

It would be better to use Git tag's versioning in kustomization-base for the users.

kustomize has already supported the use of Git refs so all we need to do is to create Git tags.

## Related repositories

- [spinnaker/kustomization-base](https://github.com/spinnaker/kustomization-base)

## Background

kleat would work well with kustomization-base, though it's not necessary. So I guess many kleat's users would use the base kustomization.

Currently, the users need to specify `bases` in this way, in order to use kustomization-base:

```yaml
bases:
- github.com/spinnaker/kustomization-base/core
```

This way might break the user's configurations because it always references `master` (or `main`) branch so the user's configurations will be affected if kustomization-base is broken.

With versioning like below:

```yaml
bases:
- github.com/spinnaker/kustomization-base/core?ref=v1.2.3
```

It allows users to use the specific version with conviction, after examining if the version works with their configurations.

## References

- [kustomization.yaml · The Kubectl Book](https://kubectl.docs.kubernetes.io/pages/examples/kustomize.html)

**Comment by ezimanyi** [comment]
@micnncim : Sounds good, thanks!  I've created `v0.1.0` with the current state of the repository.  We can bump to `v0.2.0` once spinnaker/kustomization-base#25 is merged as that's the first significant change since we've started having people use this.

**Comment by micnncim** [comment]
@ezimanyi Great work! I appreciate your quick response. You can close this issue anytime as it has met my request.

**Comment by micnncim** [comment]
@ezimanyi I think it would be better to also create GitHub releases with CHANGELOG to let users know updates.

**Comment by ezimanyi** [comment]
Yeah, that's a good point...let me create a Github action to push release notes when we publish a release.

**Comment by micnncim** [comment]
Thank you! Anything I can do to help?

**Comment by ezimanyi** [comment]
@micnncim : I was just going to look to see if there was a simple Github Action to create release notes on tag push.  [For kleat](https://github.com/spinnaker/kleat/blob/master/.github/workflows/release.yml) we use `go-releaser` which builds the binaries and also makes release notes.  Here of course we don't need to build anything so I was going to check if there was some other simple Github action that *only* created a release with release notes from a tag.

If you know of any such Github action, or want to look into that, it would definitely be helpful!  Otherwise, I'll take a look at this later this week or early next week.

**Comment by dbyron0** [comment]
From https://bsideup.github.io/posts/github_bots/, perhaps https://github.com/apps/release-drafter is helpful?

Sample config here: https://github.com/testcontainers/testcontainers-java/blob/master/.github/release-drafter.yml

**Comment by micnncim** [comment]
@ezimanyi Sounds good!

I recommend we use [git-chglog](https://github.com/git-chglog/git-chglog). It's a single binary CLI tool because of written in Go, though many popular changelog generator tools are written in Ruby or JavaScript. We can easily integrate it with GitHub Actions. Actually, I use it for my personal projects with GitHub Actions. The workflow looks like:

1. We push a Git tag
2. git-chglog generates a release note in GitHub Actions
3. [actions/create-release](https://github.com/actions/create-release) creates a GitHub release with the release note previously generated

We can generate release notes in the same format as [Kleat's ones](https://github.com/spinnaker/kleat/releases).

If you don't mind, I'd like to work on this 😄

**Comment by ezimanyi** [comment]
@micnncim : That sounds like a great plan, thanks for outlining it!  I'll assign you this issue so you can implement it.  Thanks!

**Comment by micnncim** [comment]
Now that we've merged [the PR](https://github.com/spinnaker/kustomization-base/pull/27) that supports the generation of release notes with GitHub Actions, let's complete this issue.

To maintainers: could you create the GitHub Releases for `v0.1.0` and `v0.2.0`? You can generate release notes with `git-chglog v0.1.0` and `git-chglog v0.2.0` in `spinnaker/kustomization-base`.

**Comment by maggieneterval** [comment]
@micnncim I am happy to do that; I'll close this issue once I do.

**Comment by maggieneterval** [comment]
0.1.0 and 0.2.0 have been [released](https://github.com/spinnaker/kustomization-base/releases) with changelogs!
